### ISSUE TITLE
Do not bundle source code before publishing

### ISSUE THREAD

**Issue by trivikr** [tinylibs/tinyspy#28]
### Is your feature request related to a problem? Please describe.

Tinyspy library bundles using [tsup](https://npmjs.com/package/tsup) before publishing.

The package.json scripts for reference
https://github.com/tinylibs/tinyspy/blob/0ac4b76a6b17626bd2e587392f6f621de69f3fd9/package.json#L7-L9

This reduces the install size of the published package, but affects readability and usability significantly.

```console
$ tinyspy> pnpm build

$ tinyspy> du -sh dist 
 12K    dist

$ tinyspy> ls dist 
index.cjs  index.d.ts index.js

$ tinyspy> ./node_modules/.bin/tsc -p tsconfig.json --outDir dist

$ tinyspy> du -sh dist
 20K    dist

$ tinyspy> ls dist
index.js      restoreAll.js spy.js        spyOn.js      utils.js
```

For example, I was debugging a fix for https://github.com/vitest-dev/vitest/issues/2821, and noticed that tinyspy source code is bundled, making it difficult to read through.

### Describe the solution you'd like
Just transpile the tinyspy package before publishing, so that it's still readable for someone debugging through the source code.

### Describe alternatives you've considered
Look at the source code on GitHub, and attempt to guess equivalent code in bundle

**Comment by sheremet-va** [comment]
Tinyspy started minifying after 1.0 because it hit stable (notice the word "tiny" in the name). We don't minify everything (for example, white spaces are left out for readability). I don't see any real reason to not bundle it now, your use case affects 0,01% usages (the number is from my head, the point is that it's small). So if we are going with the 80/20 rule I don't think it makes sense to remove bundle/minification step.
